export const fieldLabels: Record<string, string> = {
  username: "ชื่อผู้ใช้หรืออีเมล",
  password: "รหัสผ่าน",
  confirmPassword: "ยืนยันรหัสผ่าน",
  firstName: "ชื่อ",
  lastName: "นามสกุล",
  email: "Email",
  phone: "เบอร์โทรศัพท์",
  id: "รหัสผู้ใช้งาน",
  roomId: "ห้องเรียน",
  date: "วันที่ใช้งาน",
  start: "เวลาเริ่มต้น",
  end: "เวลาสิ้นสุด",
  attendees: "จำนวนผู้ใช้งาน",
  purpose: "วัตถุประสงค์การใช้งาน",
  equipment: "อุปกรณ์",
  note: "หมายเหตุ",
  code: "รหัสห้อง",
  name: "ชื่อห้อง",
  building: "อาคาร",
  floor: "ชั้น",
  capacity: "ความจุ",
  description: "รายละเอียด",
  image: "URL รูปภาพ",
  category: "ประเภท",
  role: "Role",
  status: "สถานะ",
};
